// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9wIrcwpTsw9Q4UHiYmhYAVR7GRLtJhZg',
    appId: '1:394967961901:web:0da57f4bf6c3eecabdc3a4',
    messagingSenderId: '394967961901',
    projectId: 'prjpab2-si61-2327240006',
    authDomain: 'prjpab2-si61-2327240006.firebaseapp.com',
    storageBucket: 'prjpab2-si61-2327240006.firebasestorage.app',
    measurementId: 'G-9J7G2HPSQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaGUSZ9sfM7_F8KzRhud-OHbHYvcubA-I',
    appId: '1:394967961901:android:80b7915506aa6768bdc3a4',
    messagingSenderId: '394967961901',
    projectId: 'prjpab2-si61-2327240006',
    storageBucket: 'prjpab2-si61-2327240006.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYXsTgXCvQn3cq2VoxLr0yK_iQKBFH76Y',
    appId: '1:394967961901:ios:4dc8cef84f3daef6bdc3a4',
    messagingSenderId: '394967961901',
    projectId: 'prjpab2-si61-2327240006',
    storageBucket: 'prjpab2-si61-2327240006.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYXsTgXCvQn3cq2VoxLr0yK_iQKBFH76Y',
    appId: '1:394967961901:ios:4dc8cef84f3daef6bdc3a4',
    messagingSenderId: '394967961901',
    projectId: 'prjpab2-si61-2327240006',
    storageBucket: 'prjpab2-si61-2327240006.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9wIrcwpTsw9Q4UHiYmhYAVR7GRLtJhZg',
    appId: '1:394967961901:web:a0b2cfeb335ea4dbbdc3a4',
    messagingSenderId: '394967961901',
    projectId: 'prjpab2-si61-2327240006',
    authDomain: 'prjpab2-si61-2327240006.firebaseapp.com',
    storageBucket: 'prjpab2-si61-2327240006.firebasestorage.app',
    measurementId: 'G-Z1MF3T617P',
  );
}
